name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  
  # Scan history + database
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1

  # Charts
  fl_chart: ^0.65.0

  # Lints
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/upload.jpg
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/classes/0.jpg
    - assets/classes/1.jpg
    - assets/classes/2.jpg
    - assets/classes/3.jpg
    - assets/classes/4.jpg
    - assets/classes/5.jpg
    - assets/classes/6.jpg
    - assets/classes/7.jpg
    - assets/classes/8.jpg
    - assets/classes/9.jpg
